- name: vars promt
  hosts: localhost
  become: yes
  vars_prompt:
    - name: USERNAME
      prompt: Please enter username
      private: false
    - name: PASSWORD
      prompt: Please enter password
      private: true
  tasks:
    - name: vars prompt example
      ansible.builtin.debug:
        msg: "Your username is {{USERNAME}} and password is {{PASSWORD}}"
